d = {'a': '아',
     'aa': '아',
     'ab': '압',
     'ah': '아흐',
     'am': '암',
     'al': '알',
     'ala': '알라',
     'ang': '앙',
     'b': '브',
     'ba': '바',
     'bach': '밧',
     'bal': '발',
     'be': '베',
     'bh': '브',
     'bha': '바',
     'bhai': '바이',
     'bhi': '비',
     'bhu': '부',
     'bi': '비',
     'bin': '빈',
     'bo': '보',
     'boo': '부',
     'bu': '부',
     'ca': '카',
     'cha': '차',
     'chai': '차이',
     'chan': '찬',
     'chau': '차우',
     'che': '체',
	 'chen': '첸',
     'chha': '차',
     'chin': '친',
     'd': '드',
     'da': '다',
     'dali': '달리',
     'dan': '단',
     'dda': '다',
     'de': '드',
     'deen': '딘',
     'dehl': '델',
     'denga': '뎅가',
     'dh': '드',
     'dha': '다',
     'dhan': '단',
     'dhi': '디',
     'dhu': '두',
     'di': '디',
     'din': '딘',
     'del':'델',
     'della': '델라',
     'den': '덴',
     'dar': '다르',
     'das': '다스',
     'dde': '데',
     'dha': '다',
     'do': '도',
     'dra': '드라',
     'du': '두',
     'dud': '둣',
     'dul': '둘',
     'dya': '댜',
     'fa': '파',
     'fan': '판',
     'ful': '풀',
     'g': '그',
     'ga': '가',
     'gal': '갈',
     'gan': '간',
     'gao': '고',
     'gap': '갑',
     'gau': '가우',
     'gha': '가',
     'gho': '고',
     'gi': '기',
     'gil': '길',
     'go': '고',
     'gow': '고',
     'gra': '그라',
     'ggu': '구',
     'h': '흐',
     'ha': '하',
     'hal': '할',
     'ham': '함',
     'han': '한',
     'hi': '히',
     'hri': '리',
     'hu': '후',
     'hul': '훌',
     'i': '이',
     'irr': '이르',
     'j': '즈',
     'ja': '자',
     'jai': '제',
     'jalingap': '잘링갑',
     'jan': '잔',
     'jee': '지',
     'jha': '자',
     'jhi': '지',
     'ji': '지',
     'jku': '지쿠',
     'jo': '조',
     'ju': '주',
     'jun': '준',
     'k': '크',
     'ka': '카',
     'kal': '칼',
     'kalam': '칼람',
     'Kalinga': '칼링가',
     'kan': '칸',
     'kar': '카르',
     'ke': '케',
     'kh': '크',
     'kha': '카',
     'khan': '칸',
     'khe': '케',
     'khile': '킬레',
     'khu': '쿠',
     'khun': '쿤',
     'ki': '키',
     'kil': '킬',
     'kin': '킨',
     'kla': '클라',
     'ko': '코',
     'kol': '콜',
     'kon': '콩',
     'kul': '쿨',
     'kya': '캬',
     'kyo': '쿄',
     'ku': '쿠',
     'kun': '쿤',
     'le': '레',
     'lee': '리',
     'la': '라',
     'lah': '라',
     'lak': '락',
     'lal': '랄',
     'lala': '랄라',
     'lalh': '랄',
     'lali': '랄리',
     'laloo': '랄루',
     'lalu': '랄루',
     'lan': '란',
     'lax': '락슈',
     'li': '리',
     'lingap': '링갑',
     'lo': '로',
     'long': '롱',
     'ma': '마',
     'maiah': '메야',
     'mal': '말',
     'mala': '말라',
     'man': '만',
     'mangaiha': '망가이',
     'me': '메',
     'meh': '메흐',
     'mehta': '메타',
     'melak': '멜락',
     'mi': '미',
     'mma': '마',
     'mo': '모',
     'mon': '몬',
     'mu': '무',
     'mul': '물',
     'mun': '문',
     'my': '미',
     'mya': '미야',
     'na': '나',
     'nam': '남',
     'nan': '난',
     'ne': '네',
     'nee': '니',
     'ney': '니',
     'ni': '니',
     'nian': '니안',
     'nni': '니',
     'no': '노',
     'non': '논',
     'nu': '누',
     'nul': '눌',
     'p': '프',
     'pa': '파',
     'pal': '팔',
     'pan': '판',
     'pang': '팡',
     'phon': '폰',
     'phoo': '풀',
     'pi': '피',
     'pil': '필',
     'pilen': '필렌',
     'poo': '푸',
     'pu': '푸',
     'qa': '카',
     'qui': '키',
     'r': '르',
     'ra': '라',
     'rag': '라그',
     'raj': '라즈',
     'ralee': '랄리',
     'ram': '람',
     'ran': '란',
     'rao': '라오',
     'rap': '랍',
     'rayen': '라옌',
     're': '르',
     'ree': '리',
     'regu': '레구',
     'rema': '레마',
     'ri': '리',
     'ril': '릴',
     'ro': '로',
     'ru': '루',
     'rud': '룻',
     'run': '룬',
     'ry': '리',
     's': '스',
     'sa': '사',
     'sai': '사이',
     'sal': '살',
     'salah': '살라',
     'san': '산',
     'sel': '셀',
     'sen': '센',
     'sh': '시',
     'sha': '샤',
     'shah': '샤',
     'shali': '샬리',
     'shan': '샨',
     'shdie': '슈디',
     'she': '쉬',
     'sheila': '실라',
     'shek': '셰크',
     'sher': '셰르',
     'shera': '셰라',
     'shetty': '셰티',
     'shi': '시',
     'shil': '실',
     'shma': '슈마',
     'shmi': '슈미',
     'shna': '슈나',
     'shnan': '슈난',
     'sho': '쇼',
     'shri': '슈리',
     'shyam': '샴',
     'shva': '슈바',
     'shwa': '슈와',
     'shwan': '슈완',
     'shtha': '슈타',
     'shu': '슈',
     'si': '시',
     'sid': '싯',
     'sim': '심',
     'singh': '싱',
     'so': '소',
     'som': '솜',
     'sou': '소',
     'ssa': '사',
     'ssain': '세인',
     'su': '수',
     'sul': '술',
     'sulo': '술로',
     'sun': '순',
     'sur': '수르',
     'swa': '스와',
     't': '트',
     'ta': '타',
     'tal': '탈',
     'tan': '탄',
     'tann': '탄',
     'tanni': '타니',     
     'te': '테',
     'ten': '텐',
     'th': '트',
     'tha': '타',
     'thalai': '탈라이',
     'than': '탄',
     'thanga': '탕가',
     'thi': '티',
     'thik': '틱',
     'thy': '티',
     'thu': '투',
     'ti': '티',
     'til': '틸',
     'tla': '탈라',
     'tta': '타',
     'ttal': '탈',
     'tte': '테',
     'tty': '티',
     'to': '토',
     'tu': '투',
     'tul': '툴',
     'ty': '티',
     'tya': '탸',
     'u': '우',
     'ud': '웃',
     'ul': '울',
     'v': '브',
     'va': '바',
     'vam': '밤',
     'van': '반',
     'vai': '배',
     'vak': '박',
     've': '베',
     'ven': '벤',
     'vi': '비',
     'vig': '비그',
     'vin': '빈',
     'vul': '불',
     'w': '우',
     'wa': '와',
     'wal': '왈',
     'wan': '완',
     'wang': '왕',
     'war': '와르',
     'we': '웨',
     'x': '슈',
     'y': '이',
     'ya': '야',
     'ye': '예',
     'yee': '이',
     'yu': '유',
     'z': '즈',
     'za': '자',
     'zan': '잔',
     'zeli': '젤리',
     'zhi': '지',
     'zi': '지',
     'zo': '조',
     'zu': '주',
     'zum': '줌',
}

class Node:
    def __init__(self, text):
        self.sourcetext = text.lower()
        if self.sourcetext in d:
            self.targettext = d[self.sourcetext]
        else:
            self.targettext = ''
        self.left = None
        self.right = None
        
    def split(self, before, after):
        src = self.sourcetext
        if not self.targettext and before + after in src:
            pos = src.index(before + after) + len(before)
            self.left = Node(src[:pos])
            self.right = Node(src[pos:])
            self.sourcetext = ''
            self.targettext = ''
        elif self.left and self.right:
            self.left.split(before, after)
            self.right.split(before, after)
        else:
            pass

    def gettranslation(self):
        if self.left or self.right:
            return self.left.gettranslation() + self.right.gettranslation()
        else:
            return self.targettext if self.targettext else self.sourcetext
        

class Tree:
    def __init__(self, word):
        self.root = Node(word)        
        
    def parse(self):
        self.root.split('', ',')
        
        for x in ['ak|ka', 'ud|di', 'am|r', 'ng|p', 'i|sh', 'na|ma', 'na|mu', 'na|s', 'na|v', 'u|mon', 'lali|t', 'u|bhai', 'a|rag', 'jai|n', 'l|ab', 'ch|ch', 'i|va', 'irr|f', 'i|thi', 'su|shmi', 'shmi|ta', 'shri|ya', 'shali|n', 'e|sh', 'i|sh', 'u|sh', 'shwa|na', 'shwa|ri', 'shwan|t', 'n|gg', 'ni|ja', 'jalingap|p', 'salah|u', 'a|maiah', 'o|dde', 'dde|go', 'ulo|cha', 'ma|nia', 'pu|tu', 'regu|na']:
            a, b = tuple(x.split('|'))
            self.root.split(a, b)
            
        # Do not sort this list alphbetically!
        for x in ['a|d', 'a|f', 'b|d', 'b|r', 'd|d', 'd|m', 'g|b', 'g|r', 'h|b', 'h|g', 'h|m', 'h|n', 'h|r', 'h|v', 'h|w', 'j|p', 'k|r', 'k|s', 'l|b', 'l|c', 'l|d', 'l|g', 'l|h', 'l|k', 'l|l', 'l|m', 'l|p', 'l|t', 'l|v', 'l|y', 'm|b', 'm|d', 'm|m', 'm|n', 'm|p', 'm|r', 'm|t', 'n|m', 'n|d', 'n|j', 'n|k', 'n|n', 'n|s', 'n|t', 'n|w', 'o|w', 'p|p', 'r|d', 'r|j', 'r|k', 'r|m', 'r|n', 'r|r', 'r|s', 'r|t', 'r|v', 's|m', 's|p', 's|w', 't|n', 'u|j', 'u|l', 'u|r', 'u|z', 'v|r', 'w|d', 'w|l', 'w|m', 'x|m', 'y|l', 'y|y', 'a|b', 'a|c', 'a|g', 'a|h', 'a|j', 'a|k', 'a|p', 'a|r', 'a|s', 'a|t', 'a|v', 'a|w', 'a|y', 'a|z', 'e|d', 'e|g', 'e|h', 'e|j', 'e|k', 'e|n', 'e|p', 'e|r', 'e|s', 'e|t', 'e|w', 'i|a', 'i|b', 'i|c', 'i|d', 'i|j', 'i|k', 'i|p', 'i|q', 'i|r', 'i|s', 'i|t', 'i|v', 'i|w', 'i|y', 'j|r', 'j|v', 'o|b', 'o|c', 'o|d', 'o|h', 'o|j', 'o|k',  'o|l', 'o|m', 'o|n', 'o|p', 'o|r', 'o|sh', 'o|y', 'o|z', 'p|r', 't|r', 'u|b', 'u|d', 'u|g', 'u|h', 'u|k', 'u|m', 'u|p', 'u|s', 'u|t', 's|k', 's|t', 'a|i', 'a|l', 'a|m', 'a|n', 'i|m', 'i|n', 'i|t', 'u|n']:
            a, b = tuple(x.split('|'))
            self.root.split(a, b)
        
    def traverse(self):
        return self.root.gettranslation()
        

def to_ko(userinput):
    result = []
    
    for x in userinput.replace('-', ' ').split():
        t = Tree(x)
        t.parse()
        result.append(t.traverse())
        
    return ' '.join(result)
    
    
if __name__ == "__main__":
    print(to_ko(input()))