# http://southasia.or.kr/bbs/board.php?bo_table=hindmark&wr_id=2&sm=3060
hindi_ko = {
    'a': '아',
    'aa': '아',
    'ab': '압',
    'ah': '아흐',
    'am': '암',
    'al': '알',
    'ala': '알라',
    'ang': '앙',
    'i': '이',
    'irr': '이르',
    'u': '우',
    'ud': '웃',
    'ul': '울',
    'ut': '웃',
    'b': '브',
    'ba': '바',
    'bach': '밧',
    'bal': '발',
    'be': '베',
    'ben': '벵',
    'bh': '브',
    'bha': '바',
    'bhai': '바이',
    'bhi': '비',
    'bhu': '부',
    'bi': '비',
    'bin': '빈',
    'bo': '보',
    'boo': '부',
    'bu': '부',
    'ca': '짜',
    'cha': '차',
    'chai': '차이',
    'chan': '짠',
    'chau': '차우',
    'che': '체',
    'chen': '첸',
    'chha': '차',
    'chin': '친',
    'd': '드',
    'da': '다',
    'dak': '닥',
    'dali': '달리',
    'dan': '단',
    'dda': '다',
    'de': '드',
    'deen': '딘',
    'dela': '델라',
    'dehl': '델',
    'delhi': '델리',
    'denga': '뎅가',
    'dh': '드',
    'dha': '다',
    'dhan': '단',
    'dhi': '디',
    'dhu': '두',
    'di': '디',
    'din': '딘',
    'de': '데',
    'del':'델',
    'della': '델라',
    'den': '덴',
    'dar': '다르',
    'das': '다스',
    'dde': '데',
    'dha': '다',
    'do': '도',
    'dra': '드라',
    'du': '두',
    'dud': '둣',
    'dul': '둘',
    'dya': '댜',
    'fa': '파',
    'fan': '판',
    'ful': '풀',
    'g': '그',
    'ga': '가',
    'gal': '갈',
    'gan': '간',
    'gao': '고',
    'gap': '갑',
    'gau': '가우',
    'ge': '게',
    'gha': '가',
    'gho': '고',
    'gi': '기',
    'gil': '길',
    'go': '고',
    'gow': '고',
    'gra': '그라',
    'gu': '구',
    'h': '흐',
    'ha': '하',
    'hal': '할',
    'ham': '함',
    'han': '한',
    'hi': '히',
    'hri': '리',
    'hu': '후',
    'hul': '훌',
    'hlo': '흘로',
    'j': '즈',
    'ja': '자',
    'jai': '제',
    'jalingap': '잘링갑',
    'jan': '잔',
    'jee': '지',
    'jha': '자',
    'jhi': '지',
    'ji': '지',
    'jku': '지쿠',
    'jo': '조',
    'ju': '주',
    'jun': '준',
    'k': '끄',
    'ka': '까',
    'kal': '깔',
    'kalam': '깔람',
    'Kalinga': '깔링가',
    'kan': '깐',
    'kar': '까르',
    'ke': '께',
    'ki': '끼',
    'kil': '낄',
    'kin': '낀',
    'kla': '끌라',
    'ko': '꼬',
    'kol': '꼴',
    'kon': '꽁',
    'kul': '꿀',
    'kya': '꺄',
    'kyo': '꾜',
    'ku': '꾸',
    'kul': '꿀',
    'kun': '꾼',
    'kh': '크',
    'kha': '카',
    'khan': '칸',
    'khe': '케',
    'khile': '킬레',
    'khu': '쿠',
    'khun': '쿤',
    'le': '레',
    'lee': '리',
    'la': '라',
    'lah': '라',
    'lak': '락',
    'lal': '랄',
    'lala': '랄라',
    'lalh': '랄',
    'lali': '랄리',
    'laloo': '랄루',
    'lalu': '랄루',
    'lan': '란',
    'lax': '락슈',
    'lakhsi': '락시',
    'li': '리',
    'lingap': '링갑',
    'lo': '로',
    'long': '롱',
    'ma': '마',
    'maiah': '메야',
    'mal': '말',
    'mala': '말라',
    'man': '만',
    'mangaiha': '망가이',
    'me': '메',
    'meh': '메흐',
    'mehta': '메타',
    'melak': '멜락',
    'mi': '미',
    'min': '만',
    'mma': '마',
    'mo': '모',
    'mon': '몬',
    'mu': '무',
    'mul': '물',
    'mun': '문',
    'my': '미',
    'mya': '미야',
    'na': '나',
    'nam': '남',
    'nan': '난',
    'ne': '네',
    'nee': '니',
    'ney': '니',
    'ni': '니',
    'nian': '니안',
    'no': '노',
    'non': '논',
    'nu': '누',
    'nul': '눌',
    'p': '쁘',
    'pa': '빠',
    'pal': '빨',
    'pan': '빤',
    'pang': '빵',
    'pi': '삐',
    'pil': '삘',
    'pilen': '삘렌',
    'phon': '폰',
    'phoo': '풀',
    'poo': '뿌',
    'pu': '뿌',
    'qa': '까',
    'qui': '끼',
    'r': '르',
    'ra': '라',
    'rag': '라그',
    'raj': '라즈',
    'ralee': '랄리',
    'ram': '람',
    'ran': '란',
    'rao': '라오',
    'rap': '랍',
    'rayen': '라옌',
    're': '르',
    'ree': '리',
    'regu': '레구',
    'rema': '레마',
    'ri': '리',
    'ril': '릴',
    'ro': '로',
    'ru': '루',
    'rud': '룻',
    'run': '룬',
    'ry': '리',
    's': '스',
    'sa': '사',
    'sai': '사이',
    'sal': '살',
    'salah': '살라',
    'san': '산',
    'sel': '셀',
    'sen': '센',
    'sha': '샤',
    'shah': '샤',
    'shali': '샬리',
    'shan': '샨',
    'shdie': '슈디',
    'she': '셰',
    'sheila': '실라',
    'shek': '셰크',
    'sher': '셰르',
    'shera': '셰라',
    'shet': '솃',
    'shi': '시',
    'shil': '실',
    'shim': '심',
    'shin': '신',
    'shma': '슈마',
    'shmi': '슈미',
    'shna': '슈나',
    'shnan': '슈난',
    'sho': '쇼',
    'shri': '슈리',
    'shyam': '샴',
    'shva': '슈바',
    'shwa': '슈와',
    'shwan': '슈완',
    'shtha': '슈타',
    'shu': '슈',
    'sh': '슈',
    'sh$': '시',
    'si': '시',
    'sid': '싯',
    'sim': '심',
    'singh': '싱',
    'so': '소',
    'som': '솜',
    'sou': '소',
    'ssa': '사',
    'ssain': '세인',
    'su': '수',
    'sul': '술',
    'sulo': '술로',
    'sun': '순',
    'sur': '수르',
    'swa': '스와',
    't': '뜨',
    'ta': '따',
    'tal': '딸',
    'tan': '딴',    
    'te': '떼',
    'ten': '뗀',
    'ti': '띠',
    'til': '띨',
    'tla': '딸라',
    'to': '또',
    'tu': '뚜',
    'tul': '뚤',
    'ty': '띠',
    'tya': '땨',
    'th': '트',
    'tha': '타',
    'thalai': '탈라이',
    'than': '탄',
    'thanga': '탕가',
    'thi': '티',
    'thik': '틱',
    'thy': '티',
    'thu': '투',
    'v': '브',
    'va': '바',
    'vam': '밤',
    'van': '반',
    'vai': '배',
    'vak': '박',
    've': '베',
    'ven': '벤',
    'vi': '비',
    'vig': '비그',
    'vin': '빈',
    'vul': '불',
    'w': '우',
    'wa': '와',
    'wal': '왈',
    'wan': '완',
    'wang': '왕',
    'war': '와르',
    'we': '웨',
    'y': '이',
    'ya': '야',
    'ye': '예',
    'yee': '이',
    'yu': '유',
    'z': '즈',
    'za': '자',
    'zan': '잔',
    'zeli': '젤리',
    'zhi': '지',
    'zi': '지',
    'zo': '조',
    'zu': '주',
    'zum': '줌',
}

splitpoint = [
    ['|,'],
    ['a|ku', 'a|rag', 'ak|ka', 'a|v', 'a|w', 'a|maiah', 'am|r', 'ch|ch', 'dde|go', 'e|sh', 'i|sh', 'i|sh', 'i|va', 'irr|f', 'i|thi', 'jai|n', 'jalingap|p', 'lali|t', 'l|ab', 'ma|nia', 'na|ma', 'na|mu', 'na|s', 'na|v', 'ng|p', 'ng|g', 'ni|ja', 'o|dde', 'ulo|cha', 'o|sh', 'pu|tu', 'regu|na', 'su|shmi', 'shmi|ta', 'shri|ya', 'shali|n', 'shwa|na', 'shwa|ri', 'shwan|t', 'salah|u', 'u|bhai', 'u|mon', 'u|sh', 'ud|di', ],
    ['b|d', 'b|r', 'd|d', 'd|m', 'g|b', 'g|g', 'g|r', 'h|b', 'h|g', 'h|m', 'h|n', 'h|r', 'h|v', 'h|w', 'j|p', 'k|r', 'k|s', 'l|b', 'l|c', 'l|d', 'l|g', 'l|h', 'l|k', 'l|l', 'l|m', 'l|p', 'l|t', 'l|v', 'l|y', 'm|b', 'm|d', 'm|l', 'm|m', 'm|n', 'm|p', 'm|r', 'm|t', 'n|m', 'n|d', 'n|j', 'n|k', 'n|n', 'n|s', 'n|t', 'n|w', 'p|p', 'r|d', 'r|j', 'r|k', 'r|m', 'r|n', 'r|r', 'r|s', 'r|t', 'r|v', 's|m', 's|p', 's|w', 't|n', 't|t', 'v|r', 'w|d', 'w|l', 'w|m', 'x|m', ],
    ['n|g', ],
    ['a|d', 'a|f', 'o|w', 'u|j', 'u|l', 'u|r', 'u|w', 'u|z', 'y|l', 'y|y', ],
    ['a|b', 'a|c', 'a|g', 'a|h', 'a|j', 'a|k', 'a|p', 'a|r', 'a|s', 'a|t', 'a|v', 'a|w', 'a|y', 'a|z', 'e|d', 'e|h', 'e|g', 'e|j', 'e|k', 'e|n', 'e|p', 'e|r', 'e|s', 'e|t', 'e|v', 'e|w', 'i|a', 'i|b', 'i|c', 'i|d', 'i|j', 'i|k', 'i|p', 'i|q', 'i|r', 'i|s', 'i|t', 'i|v', 'i|w', 'i|y', 'j|r', 'j|v', 'o|b', 'o|c', 'o|d', 'o|h', 'o|j', 'o|k', 'o|l', 'o|m', 'o|n', 'o|p', 'o|r', 'o|t', 'o|y', 'o|z', 'p|r', 't|r', 'u|b', 'u|d', 'u|g', 'u|h', 'u|k', 'u|m', 'u|p', 'u|s', 'u|t', 's|k', 's|t', ],
    ['a|i', 'a|l', 'a|m', 'a|n', 'i|m', 'i|n', 'i|t', 'u|n', 'y|s',]
]


class Tree:
    def __init__(self, text):
        self.sourcetext = text.lower()
        if self.sourcetext in hindi_ko:
            self.targettext = hindi_ko[self.sourcetext]
        elif self.sourcetext.replace('$', '') in hindi_ko:
            self.targettext = hindi_ko[self.sourcetext.replace('$', '')]
        else:
            self.targettext = ''
        self.left = None
        self.right = None
        
    def split(self, before, after):
        src = self.sourcetext
        if not self.targettext and before + after in src:
            pos = src.index(before + after) + len(before)
            self.left = Tree(src[:pos])
            self.right = Tree(src[pos:])
            self.sourcetext = ''
            self.targettext = ''
        elif self.left and self.right:
            self.left.split(before, after)
            self.right.split(before, after)
        else:
            pass

    def gettranslation(self):
        if self.left or self.right:
            return self.left.gettranslation() + self.right.gettranslation()
        else:
            return self.targettext if self.targettext else self.sourcetext
       
    def parse(self, splitpoint):
        for x in splitpoint:
            for y in x:
                a, b = tuple(y.split('|'))
                self.split(a, b)
        

def to_ko(userinput):
    result = []
    
    for word in userinput.replace('-', ' ').split():
        root = Tree(word + '$') 
        root.parse(splitpoint)
        result.append(root.gettranslation().replace('$', ''))
        
    return ' '.join(result)
    
    
if __name__ == "__main__":
    print(to_ko(input()))