import indian
import indiantree

def test(name):
    print(name, ':', indian.to_ko(name), ';', indiantree.to_ko(name))


test("Sundar Pichai")
test("Parag Agrawal")
test("Shantanu Narayen")
test("Satya Narayana Nadella")
test("Nikesh Arora")
test("Alphonsa Muttathupadathu")
test("Soumya Swaminathan")
test("Shilpa Shetty")
test("Zubin Mehta")
test("Pranav Mistry")
test("Leena Nair")
test("Amrita Sher-Gil")
test("Ahmed Salman Rushdie")
test("Avul Pakir Jainulabdeen Abdul Kalam")
test("Spivak, Gayatri")
test("Ritesh Modi")
test("Sushmita Sen")
test("Mohammed Aamir Hussain Khan")
test("Shahrukh Khan")
test("Amitabh Bachchan")
test("Hrithik Roshan")
test("Salman Khan")
test("Abhishek Bachchan")
test("Irrfan Khan")
test("Shri Kapil Sibal")
test("Rahul Gandhi")
test("Gita Gopinath")
test("Nazir Ahmad Dehlv")
test("Neetu Chandra")
test("Nandita Das")
test("Neha Dhupia")
test("Radhika Madan")
test("Rajkumar Yadav")
test("Rakul Preet Singh")
test("Arjun Rampal")
test("Suzanna Arundhati Roy")
test("Manoj Bajpayee")
test("Chandra Talpade Mohanty")
test("Mira Nair")
test("Swara Bhaskar")
test("Amitabh Bachchan")
test("Kabir Bedi")
test("Shriya Saran")
test("Shiney Ahuja")
test("Konkona Sen Sharma")
test("Mallika Sherawat")
test("Shilpa Shukla")
test("Madhur Jaffrey")
test("Tannishtha Chatterjee")
test("Gauri Khan")
test("Parvin Dabas")
